//
//  FlightDetailTests.swift
//
//  Created by Tarsha De Souza on 02/07/2020.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Globile Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
@testable import <MODULE_NAME>

class FlightDetailInteractorTests: XCTestCase {
    
	private var presenter: FlightDetailPresenterMock!
	private var interactor: FlightDetailBusinessLogicProtocol!

	override func setUp() {
        super.setUp()
		presenter = FlightDetailPresenterMock()
		interactor = FlightDetailInteractor(presenter: presenter)
	}
	
	override func tearDown() {
		presenter = nil
		interactor = nil
        super.tearDown()
	}

	func testDoSomethingSuccess() {
		let request = FlightDetail.Model.Request()
		_ = interactor.doSomething(request: request)
		XCTAssertTrue(presenter.presentResponseCalled, "Interactor did not call presenter when after successful call")
	}

}
