//
//  FlightInfoMocks.swift
//
//  Created by Tarsha de Souza on 1/7/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Globile Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import <MODULE_NAME>

class FlightInfoPresenterMock: FlightInfoPresenterProtocol {
	
		var presentResponseCalled = false
		var presentErrorCalled = false
		
		func presentSomething(response: FlightInfo.Model.Response) {
			presentResponseCalled = true
		}
		
		func present(error: Error) {
			presentErrorCalled = true
		}
}
